services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: clinical-calculators:built
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      [
        "uvicorn",
        "api.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
